
/*
 * header 头部数据
*/
//所有地区
export const areaList = [
  {id:1,name:'北京'},
  {id:2,name:'上海'},
  {id:3,name:'天津'},
  {id:4,name:'重庆'},
  {id:5,name:'河北'},
  {id:6,name:'山西'},
  {id:7,name:'河南'},
  {id:8,name:'辽宁'},
  {id:9,name:'吉林'},
  {id:10,name:'黑龙江'},
  {id:11,name:'内蒙古'},
  {id:12,name:'江苏'},
  {id:13,name:'山东'},
  {id:14,name:'安徽'},
  {id:15,name:'浙江'},
  {id:16,name:'福建'},
  {id:17,name:'湖北'},
  {id:18,name:'湖南'},
  {id:19,name:'广东'},
  {id:20,name:'广西'},
  {id:21,name:'江西'},
  {id:22,name:'四川'},
  {id:23,name:'海南'},
  {id:24,name:'贵州'},
  {id:25,name:'云南'},
  {id:26,name:'西藏'},
  {id:27,name:'陕西'},
  {id:28,name:'甘肃'},
  {id:29,name:'青海'},
  {id:30,name:'宁夏'},
  {id:31,name:'新疆'},
  {id:32,name:'港澳'},
  {id:33,name:'台湾'},
  {id:34,name:'钓鱼岛'},
  {id:35,name:'海外'}
]
//企业采购数据
export const enterpriseData = ['企业购','商用场景馆','工业品','礼品卡'];
//客户服务数据
export const customerData = [
  {
    name:'客户',
    list:['帮助中心','售后客服','在线客户','意见建议','电话客服','客服邮箱','金融咨询','全球售客服']
  },
  {
    name:'商户',
    list:['合作招商','学习中心','商家后台','商家帮助']
  }
]
//网站导航数据
export const siteNavData = [
  {
    name:"特色主题",
    list:[
      "天天试用","天天金融","全球售","国际站","天天会员","天天预售","买什么","俄语站","装机大师",
      "0元评测","定期送","港澳售","优惠券","秒杀","闪购","印尼站","天天金融科技","In货推荐","陪伴计划","出海招商"
    ]
  },
  {
    name:"行业频道",
    list:[
      "手机","智能数码","玩3C","电脑办公","家用电器","天天智能","服装城","天天生鲜","家装城",
      "母婴","食品","农资频道","整车","图书","天天元器件"
    ]
  },
  {
    name:"生活服务",
    list:[
      "天天众筹","白条","天天金融App","天天小金库","理财","智能家电","话费","水电煤","彩票",
      "旅行","机票酒店","电影票","天天到家","游戏" 
    ]
  },
  {
    name:"更多精选",
    list:[
      "合作招商","天天通信","天天E卡","企业采购","服务市场","办公生活馆","乡村招募","校园加盟",
      "京友邦","天天社区","游戏社区","知识产权维权"
    ]
  }
]



/*
 * top 搜索区域数据
*/
//热搜
export const hotSearch = {
  hotRecommend:["手机狂欢日","卫浴王者站","数码交流"],
  hotWord:["小米8","电脑组件","0元试用","车厘子","MoveFree","空调钜惠","乳品冲调","笔记本"]
}
//nav导航栏数据
export const navItem = {
  "group1":["秒杀","优惠券","PLUS会员","闪购"],
  "group2":["拍卖","天天服饰","天天超市","生鲜"],
  "group3":["全球购","天天金融"]
}



/*
 * main 轮播图区域数据
*/
//菜单栏
export const mainMenu = [
  {
    _id:1,
    item:["家用电器"],
    data:{
      mItem:["家用电器"],
    }
  },
  {
    _id:2,
    item:["手机","运营商","数码"],
    data:{
      mItem:["手机运营商数码"],
    }
  },
  {
    _id:3,
    item:["电脑","办公"],
    data:{
      mItem:["电脑办公"],
    }
  },
  {
    _id:4,
    item:["家居","家具","家装","厨具"],
    data:{
      mItem:["家居家具家装厨具"],
    }
  },
  {
    _id:5,
    item:["男装","女装","童装","内衣"],
    data:{
      mItem:["男装女装童装内衣"],
    }
  },
  {
    _id:6,
    item:["美妆","个护清洁","宠物"],
    data:{
      mItem:["美妆个护清洁宠物"],
    }
  },
  {
    _id:7,
    item:["女鞋","箱包","钟表","珠宝"],
    data:{
      mItem:["女鞋箱包钟表珠宝"],
    }
  },
  {
    _id:8,
    item:["男鞋","运动","户外"],
    data:{
      mItem:["男鞋运动户外"],
    }
  },
  {
    _id:9,
    item:["房产","汽车","汽车用品"],
    data:{
      mItem:["房产汽车汽车用品"],
    }
  },
  {
    _id:10,
    item:["母婴","玩具乐器"],
    data:{
      mItem:["母婴玩具乐器"],
    }
  },
  {
    _id:11,
    item:["食品","酒类","生鲜","特产"],
    data:{
      mItem:["食品酒类生鲜特产"],
    }
  },
  {
    _id:12,
    item:["艺术","礼品鲜花","农资绿植"],
    data:{
      mItem:["艺术礼品鲜花农资绿植"],
    }
  },
  {
    _id:13,
    item:["医药保健","计生情趣"],
    data:{
      mItem:["医药保健计生情趣"],
    }
  },
  {
    _id:14,
    item:["图书","音像","电子书"],
    data:{
      mItem:["图书音像电子书"],
    }
  },
  {
    _id:15,
    item:["机票","酒店","旅游","生活"],
    data:{
      mItem:["机票酒店旅游生活"],
    }
  },
  {
    _id:16,
    item:["理财","众筹","白条","保险"],
    data:{
      mItem:["理财众筹白条保险"],
    }
  },
  {
    _id:17,
    item:["安装","维修","清洗保养"],
    data:{
      mItem:["安装维修清洗保养"],
    }
  }
]
//轮播图
export const swiperItem = [
  {
    _id:1000,
    name:"大屏电视",
    src:"dianshi.jpg"
  },
  {
    _id:1001,
    name:"扫地机器人",
    src:"jiqiren.jpg"
  },
  {
    _id:1002,
    name:"澄阳湖大闸蟹",
    src:"pangxie.jpg"
  },
  {
    _id:1003,
    name:"音箱耳机",
    src:"yinxiang.jpg"
  }
]
//广告图
export const banner = [
  {
    _id:1,
    name:"潮流电子",
    src:"1_190x150.jpg"
  },
  {
    _id:2,
    name:"空有福利",
    src:"2_190x150.jpg"
  },
  {
    _id:3,
    name:"买框架送镜片",
    src:"3_190x150.jpg"
  }
]
//新闻-公告
export const news = [
  {
    _id:1,
    data:["百万阶梯券企业专享","家电放价抢万台815元空调","赛格威平衡轮W1 即踩即走","奥妙-向伟大的母亲致净"]
  },
  {
    _id:2,
    data:[
      "京东PLUS会员权益更新及会费调整",
      "京东启用全新客服电话“950618”",
      "关于召回普利司通（天津）轮胎有限公司2个规格乘用车轮胎的公告",
      "京东物流推出配送员统一外呼电话“95056”"
    ]
  }
]
//服务
export const service = [
  {
    _id:1,
    name:"话费",
    icon:"phone"
  },
  {
    _id:2,
    name:"机票",
    icon:"rocket"
  },
  {
    _id:3,
    name:"酒店",
    icon:"home"
  },
  {
    _id:4,
    name:"游戏",
    icon:"rocket"
  },
  {
    _id:5,
    name:"企业购",
    icon:"layout"
  },
  {
    _id:6,
    name:"加油卡",
    icon:"exception"
  },
  {
    _id:7,
    name:"电影票",
    icon:"eye"
  },
  {
    _id:8,
    name:"火车票",
    icon:"notification"
  },
  {
    _id:9,
    name:"众筹",
    icon:"bank"
  },
  {
    _id:10,
    name:"理财",
    icon:"pay-circle"
  },
  {
    _id:11,
    name:"礼品卡",
    icon:"switcher"
  },
  {
    _id:12,
    name:"白条",
    icon:"gift"
  }
]

